CONNECTION_URL=jdbc:mysql://localhost:3306/nautilus_db
AMMINISTRAZIONE_USER=amministrazione_user
AMMINISTRAZIONE_PASS=amministrazione_pass
CLIENTE_USER=cliente_user
CLIENTE_PASS=cliente_pass
ISTRUTTORE_USER=istruttore_user
ISTRUTTORE_PASS=istruttore_pass
LOGIN_USER=login_user
LOGIN_PASS=login_pass